<?php

namespace ContainerLtfjgGX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KC_SKugService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KC.sKug' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KC.sKug'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CoworkingController::delete' => ['privates', '.service_locator.008Ot2C', 'get_ServiceLocator_008Ot2CService', true],
            'App\\Controller\\CoworkingController::edit' => ['privates', '.service_locator.008Ot2C', 'get_ServiceLocator_008Ot2CService', true],
            'App\\Controller\\CoworkingController::index' => ['privates', '.service_locator.35EpA24', 'get_ServiceLocator_35EpA24Service', true],
            'App\\Controller\\CoworkingController::new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CoworkingController::show' => ['privates', '.service_locator.MyXe6oB', 'get_ServiceLocator_MyXe6oBService', true],
            'App\\Controller\\InscriptionController::new' => ['privates', '.service_locator.i9UL4NH', 'get_ServiceLocator_I9UL4NHService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\UserBackController::delete' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserBackController::edit' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserBackController::index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserBackController::new' => ['privates', '.service_locator.riGN6sa', 'get_ServiceLocator_RiGN6saService', true],
            'App\\Controller\\UserBackController::show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\UserProfilController::edit' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\CoworkingController:delete' => ['privates', '.service_locator.008Ot2C', 'get_ServiceLocator_008Ot2CService', true],
            'App\\Controller\\CoworkingController:edit' => ['privates', '.service_locator.008Ot2C', 'get_ServiceLocator_008Ot2CService', true],
            'App\\Controller\\CoworkingController:index' => ['privates', '.service_locator.35EpA24', 'get_ServiceLocator_35EpA24Service', true],
            'App\\Controller\\CoworkingController:new' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\CoworkingController:show' => ['privates', '.service_locator.MyXe6oB', 'get_ServiceLocator_MyXe6oBService', true],
            'App\\Controller\\InscriptionController:new' => ['privates', '.service_locator.i9UL4NH', 'get_ServiceLocator_I9UL4NHService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.pXhSQsU', 'get_ServiceLocator_PXhSQsUService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.kdKsWx5', 'get_ServiceLocator_KdKsWx5Service', true],
            'App\\Controller\\UserBackController:delete' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserBackController:edit' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\UserBackController:index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\UserBackController:new' => ['privates', '.service_locator.riGN6sa', 'get_ServiceLocator_RiGN6saService', true],
            'App\\Controller\\UserBackController:show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\UserProfilController:edit' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\CoworkingController::delete' => '?',
            'App\\Controller\\CoworkingController::edit' => '?',
            'App\\Controller\\CoworkingController::index' => '?',
            'App\\Controller\\CoworkingController::new' => '?',
            'App\\Controller\\CoworkingController::show' => '?',
            'App\\Controller\\InscriptionController::new' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\UserBackController::delete' => '?',
            'App\\Controller\\UserBackController::edit' => '?',
            'App\\Controller\\UserBackController::index' => '?',
            'App\\Controller\\UserBackController::new' => '?',
            'App\\Controller\\UserBackController::show' => '?',
            'App\\Controller\\UserProfilController::edit' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CoworkingController:delete' => '?',
            'App\\Controller\\CoworkingController:edit' => '?',
            'App\\Controller\\CoworkingController:index' => '?',
            'App\\Controller\\CoworkingController:new' => '?',
            'App\\Controller\\CoworkingController:show' => '?',
            'App\\Controller\\InscriptionController:new' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\UserBackController:delete' => '?',
            'App\\Controller\\UserBackController:edit' => '?',
            'App\\Controller\\UserBackController:index' => '?',
            'App\\Controller\\UserBackController:new' => '?',
            'App\\Controller\\UserBackController:show' => '?',
            'App\\Controller\\UserProfilController:edit' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
