<?php

namespace ContainerLtfjgGX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoworking2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MyXe6oB.App\Entity\Coworking' shared service.
     *
     * @return \App\Entity\Coworking
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.MyXe6oB": it references class "App\\Entity\\Coworking" but no such service exists.');
    }
}
