<?php

namespace ContainerOOLUGJK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_008Ot2CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.008Ot2C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.008Ot2C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'coworking' => ['privates', '.errored..service_locator.008Ot2C.App\\Entity\\Coworking', NULL, 'Cannot autowire service ".service_locator.008Ot2C": it references class "App\\Entity\\Coworking" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'coworking' => 'App\\Entity\\Coworking',
            'entityManager' => '?',
        ]);
    }
}
