<?php

namespace ContainerOOLUGJK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MyXe6oBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MyXe6oB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MyXe6oB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'coworking' => ['privates', '.errored..service_locator.MyXe6oB.App\\Entity\\Coworking', NULL, 'Cannot autowire service ".service_locator.MyXe6oB": it references class "App\\Entity\\Coworking" but no such service exists.'],
        ], [
            'coworking' => 'App\\Entity\\Coworking',
        ]);
    }
}
