<?php

namespace ContainerOOLUGJK;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_35EpA24Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.35EpA24' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.35EpA24'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'coworkingRepository' => ['privates', 'App\\Repository\\CoworkingRepository', 'getCoworkingRepositoryService', true],
        ], [
            'coworkingRepository' => 'App\\Repository\\CoworkingRepository',
        ]);
    }
}
