<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLtfjgGX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLtfjgGX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLtfjgGX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLtfjgGX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLtfjgGX\App_KernelDevDebugContainer([
    'container.build_hash' => 'LtfjgGX',
    'container.build_id' => '8ee55865',
    'container.build_time' => 1709424370,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLtfjgGX');
